### PR TITLE
The big update (TG rebase update)

### PR DESCRIPTION
**Pull request by Jalleo**
Okay some things are incorrectly updated for some reason which means it wont merge I shall check that out in the morning.

Things to be aware of:
Storage updated to the refactor that kevinz000 did some things are still buggy there
server stuff changed from webhook to other stuff
A whole lot of other stuff changed and devices are removed all those paths are now /item/whatever

### CODE REVIEW

**Comment by Jalleo** [comment]
I need to w only need to go through the objects to see which have broken in regards to their functionality and see how to fix them. All consoles at the moment from ST13 are broken due to a TG refactor with consoles. UI stuff (html window code for each object) is all meant to be in a certain proc now. Its more modular and OOP friendly long term. I will push those updates toward the end of the week.

**Comment by Jalleo** [comment]
The failed checks are due to older unused maps that have pathing issues. I am keeping them in until I have been told whether we want to keep em or not.

**Comment by nichlas0010** [comment]
🤔

**Comment by Jalleo** [comment]
Its all due to a particular issue with travis and I am consulting with coderbus about it no flipping idea what is causing it. Something far from the cause it seems. Likely timer related trying to hunt it down.

**Comment by nichlas0010** [comment]
*Doesn't compile*
*kmc merges*
💯

**Pull request merged**
